---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: eslint
  image: marcbachmann/eslint:4.19.1
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

- name: npm-install
  image: node:10-alpine
  commands: ["npm install"]

- name: test
  image: node:10-alpine
  commands: ["npm run test -s"]

- name: release
  image: livingdocs/semantic-release:v1.0.0
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

trigger:
  event: [push]
---
kind: signature
hmac: 949c91e179f54e8c1b67153d2e4401cbf91cd968be3fb660d452786c058b0818

...
